// Define page routes here
export enum ROUTE_KEYS {
  SIGN_IN = "/sign-in",
  SUCCESSFUL_GOOGLE_AUTH = "/oauth/callback",
  FAILED_GOOGLE_AUTH = "/auth/error",
  ACCOUNT_ACTIVATION = "/verify",
  SIGN_UP = "/sign-up",
  RESET_PASSWORD = "/reset-password",
  FORGOT_PASSWORD = "/forgot-password",
  USER_OPTION = "/user-option",
  OVERVIEW = "overview",
  ORDERS = "orders",
  JOBS = "jobs",
  SETTINGS = "settings",
  BIDDING = "bidding",
  NOTIFICATIONS = "/notifications",
  HOME_OWNER_FORM = "/home-owner-form",
  INSTALLER_FORM = "/installer-form-one",
  INSTALLER_FORM_TWO = "/installer-form-two",
  INSTALLER_FORM_THREE = "/installer-form-three",
  COMPONENTS = "components",
  HOME_OWNER_ROOT = "/home-owner",
  INSTALLER_ROOT = "/installer",
}
