// Define page routes here
export enum ROUTE_KEYS {
  SIGN_IN = "/sign-in",
  SUCCESSFUL_GOOGLE_AUTH = "/oauth/callback",
  FAILED_GOOGLE_AUTH = "/auth/error",
  ACCOUNT_ACTIVATION = "/verify",
  SIGN_UP = "/sign-up",
  RESET_PASSWORD = "/reset-password",
  FORGOT_PASSWORD = "/forgot-password",
  USER_OPTION = "/user-option",
  OVERVIEW = "overview",
  SCHEDULING = "scheduling",
  BIDDING = "bidding",
  SETTINGS = "settings",
  NOTIFICATIONS = "notifications",
  HOME_OWNER_FORM = "/home-owner/home-owner-form",
  INSTALLER_FORM_ONE = "/installer/step-one",
  INSTALLER_FORM_TWO = "/installer/step-two",
  INSTALLER_FORM_THREE = "/installer/step-three",
  COMPONENTS = "components",
  HOME_OWNER_ROOT = "/home-owner",
  INSTALLER_ROOT = "/installer",
  PROJECT_TRACKER = "project-tracker",
  PROJECT_MANAGER = "project-manager",
  WALLET = "wallet",
}
