export const IMAGE_URLS = {
  logo: "/images/gosolar-logo.png",
  hero: "/images/hero-img.png",
  heroUserImg1: "/images/hero-user-1.png",
  heroUserImg2: "/images/hero-user-2.png",
  heroUserImg3: "/images/hero-user-3.png",
  stripeIllustration: "/images/powerup-illustration-img.png",
  compareQuotesImg: "/images/compare-quotes-illustration-img.png",
  tellUsImg: "/images/tellus-card-illustration-img.png",
  bookYourInstallerImg: "/images/book-card-illustration-img.png",
  trackYourProjectImg: "/images/track-proj-card-illustration-img.png",
  celebrateEnergyIndependenceImg:
    "/images/celebrate-energy-illustration-img.png",
  installSolar: "/images/install-solar-img.png",
  contractorsImg: "/images/contractors-img.png",
  businessCommercialImg: "/images/business-commercial-img.png",
  homeOwnerImg: "/images/home-owner-img.png",
  solarHouseWithCloudImg: "/images/solar-house-with-cloud.png",
  quoteImg: "/images/quote-img.png",
  homeAndBusinessImg: "/images/home-business-img.png",
  blogImg: "/images/blog-one-img.png",
  linkedInLogo: "/images/linkedin-logo.png",
  instagramLogo: "/images/instagram-logo.png",
  xLogo: "/images/x-logo.png",
  gmailLogo: "/images/gmail-logo.png",
  poorElectricityImg: "/images/poor-electricity-img.png",
  joinUsImg: "/images/join-us-img.png",
  standForImg: "/images/stand-for-img.png",
  justiceScaleImg: "/images/justice-scale-img.png",
  handGlobeImg: "/images/hand-globe-img.png",
  starThumbImg: "/images/star-thumb-img.png",
  handBulbImg: "/images/hand-bulb-img.png",
  whyGoSolarImg: "/images/why-gosolar-img.png",
  blogTwoImg: "/images/blog-two-img.png",
  faqBannerImg: "/images/faq-banner-img.png",
  hubImg: "/images/hub-img.png",
  installerStoryImg: "/images/installer-story-img.png",
  powerupCarrer: "/images/powerup-carrer-img.png",
};
